#llama al programita cgdb que a su vez invoca al gdb d earm con un archivo de configuracino muyyy basico.. why? porque el cgdb es mas bonito que el gdb -tui pelado y puedo hacer shortcuts de teclado, definir breaks etc mas rapido...
cgdb -d arm-none-eabi-gdb ./gcc/out.axf -q --command=tools/reset.gdb
